import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import Script from "next/script";

// const geistSans = Geist({
// 	variable: "--font-geist-sans",
// 	subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
// 	variable: "--font-geist-mono",
// 	subsets: ["latin"],
// });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="no-js">
			<head>
				<meta charSet="UTF-8" />
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<title>MIVEILLE | rPalm</title>
				<meta
					name="keywords"
					content="scroll animation, grid, gsap, 3d, filter"
				/>
				<meta name="author" content="rPalm" />
				<link rel="shortcut icon" href="favicon.ico" />
				<link
					rel="stylesheet"
					href="https://use.typekit.net/pxn8wdc.css"
				/>
				<Script id="set-js">
					{`document.documentElement.className = "js";`}
				</Script>
			</head>
			{/* <body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			> */}
			{children}
			{/* </body> */}
		</html>
	);
}
